NHSDigital/eps-prescription-status-update-api

.github/workflows/ci.yml, .github/workflows/release.yml
- disable mutual TLS for now
- disable PROD deployment for now
=> Chore: [AEA-0000] - disable mutual tls and prod deployments

SAMtemplates/state_machines/state_machine_resources.yaml
- Updates State Machine policy with additional permissions
=> Fix: [AEA-3831] - Fix state machine permissions

SAMtemplates/state_machines/state_machine_resources.yaml
- adds permissions to cope with stacks being deleted and recreated
=> Fix: [AEA-0000] - fix permissions for logs for state machines

.github/scripts/delete_stacks.sh, .github/workflows/ci.yml, .github/workflows/delete_old_cloudformation_stacks.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml
- enable mutual TLS on main deployments
- delete apigee deployments for closed pull requests
=> Update: [AEA-0000] - enable mutual TLS and delete old apigee deployments

.github/scripts/deploy_api.sh, .github/workflows/release.yml
=> Build: [AEA-4022] - Reorders Release Steps

SAMtemplates/tables/main.yaml
- change to on demand payment for dynamodb table
=> Fix: [AEA-0000] - change to pay per request for dynamodb

.github/scripts/get_target_deployed_tag.sh
- fix getting prod and int deployed tag
=> Fix: [AEA-0000] - fix getting prod and int deployed tag

.github/workflows/sam_package_code.yml, .github/workflows/sam_release_code.yml, pyproject.toml
- use proxygen version from poetry.lock for deployment so it is a fixed version
=> Fix: [AEA-0000] - fix proxygen version used in deployment

packages/specification/eps-prescription-status-update-api.yaml
**Remove items from this list if they are not relevant. Remove this line once this has been done**
- :exclamation: Breaking Change
- :sparkles: New Feature
- :warning: Potential issues that might be caused by this change
Add any summary information of what is in the change. **Remove this line if you have nothing to add.**
Pull requests should be named using the following format:
```text
Tag: [AEA-NNNN] - Short description
```
Tag can be one of:
- `Fix` - for a bug fix. (Patch release)
- `Update` - either for a backwards-compatible enhancement or for a rule change that adds reported problems. (Patch release)
- `New` - implemented a new feature. (Minor release)
- `Breaking` - for a backwards-incompatible enhancement or feature. …
=> Docs: [AEA-4024] - Fixed UKCore version and inbound message type in docs

packages/updatePrescriptionStatus/src/validation/fields.ts, packages/updatePrescriptionStatus/tests/validation/testRequestFieldValidation.test.ts
- make getting array elements safe in checking for elements
=> Fix: [AEA-4019] - fix response when bad json sent

.github/scripts/delete_stacks.sh
- delete sandbox stacks on apigee
=> Fix: [AEA-0000] - delete sandbox stacks on apigee

.github/scripts/delete_stacks.sh
=> Fix: [AEA-0000] - delete aws sandbox stacks

.github/workflows/ci.yml
- error if can not get next tag on merge to main
=> Fix: [AEA-0000] - error if can not get next tag

.github/scripts/deploy_api.sh
**Remove items from this list if they are not relevant. Remove this line once this has been done**
- :exclamation: Breaking Change
- :sparkles: New Feature
- :warning: Potential issues that might be caused by this change
Add any summary information of what is in the change. **Remove this line if you have nothing to add.**
Pull requests should be named using the following format:
```text
Tag: [AEA-NNNN] - Short description
```
Tag can be one of:
- `Fix` - for a bug fix. (Patch release)
- `Update` - either for a backwards-compatible enhancement or for a rule change that adds reported problems. (Patch release)
- `New` - implemented a new feature. (Minor release)
- `Breaking` - for a backwards-incompatible enhancement or feature. …
=> Build: [AEA-0000] - Setup spec deployment during INT deployment

SAMtemplates/apis/main.yaml
- fix status endpoint following refactor
=> Fix: [AEA-0000] - fix status endpoint

packages/specification/eps-prescription-status-update-api.yaml
=> Docs: [AEA-4092] - Add 'You can' Bullet Points to Spec Overview

.github/workflows/pull_request.yml, Makefile, SAMtemplates/tables/main.yaml
- use a custom role for dynamo scaling
- add scaling on all write indexes and nhs number read index
=> Fix: [AEA-4094] - fix dynamo scaling

packages/specification/eps-prescription-status-update-api.yaml
Resolves issues raised in review comments.
=> Docs: [AEA-4092] - Resolve Review Comments

package-lock.json, packages/specification/eps-prescription-status-update-api.yaml, packages/updatePrescriptionStatus/src/updatePrescriptionStatus.ts, packages/updatePrescriptionStatus/tests/utils/testUtils.ts
- pass the application name from apigee to backend in a header
- store the application name in dynamodb
=> Fix: [AEA-4107] - store the application name calling the api

package-lock.json, package.json
- latest semantic-release needs latest conventional-changelog-eslint
=> Fix: [AEA-0000] - upgrade to latest conventional-changelog-eslint

.vscode/eps-prescription-status-update-api.code-workspace, packages/capabilityStatement/src/apim-medicines-prescriptionstatusupdate.json
- fix typo in capability statement
=> Fix: [AEA-0000] - fix typo in capability statement

.github/scripts/delete_stacks.sh
- Updates delete_stacks script to cover cpsu proxies
=> Fix: [AEA-0000] - Updates delete_stacks to cover CPSU

packages/cpsuLambda/src/schema/format_1/transformer.ts, packages/cpsuLambda/tests/format_1/example_response.json
Added missed field "status" to the output of CPSU so it should be accepted by the PSU lambda.
=> Fix: [AEA-4177] - Added Task.status to CPSU output

SAMtemplates/state_machines/Format1UpdatePrescriptionsStatusStateMachine.asl.json
- fix hard coded function name in step function
=> Fix:  [AEA-0000] - fix hard coded function name in step funciton

packages/cpsuLambda/src/schema/format_1/validator.ts, packages/cpsuLambda/tests/format_1/example_request.json, packages/cpsuLambda/tests/format_1/example_response.json, packages/cpsuLambda/tests/testHandler.test.ts
=> Fix: [AEA-4102] - Made CPSU format 1 ignore messages for non nhs england patients

packages/updatePrescriptionStatus/src/updatePrescriptionStatus.ts, packages/updatePrescriptionStatus/src/utils/databaseClient.ts, packages/updatePrescriptionStatus/tests/testDatabaseClient.test.ts
- move logger in  updatePrescriptionStatus lambda so only initialized once to help performance
=> Fix: [AEA-0000] - move logger in updatePrescriptionStatus lambda so only initialized once

.github/workflows/ci.yml, .github/workflows/release.yml
- parse releaes.config.js to get release tag format instead of .releaserc
=> Fix: [AEA-0000] - fix getting tag format in release pipeline

packages/specification/eps-prescription-status-update-api.yaml
Update OAS to reflect PSU as a silver service
=> Docs: [AEA-4280] - Update OAS to reflect silver service

packages/specification/eps-custom-prescription-status-update-api.yaml
Update OAS to reflect CPSU silver service level
=> Docs: [AEA-4281] - Update OAS to reflect silver service level

.github/workflows/ci.yml
- set correct role for merge to main workflow
=> Fix: [AEA-0000] - fix deployments using proxygen

packages/updatePrescriptionStatus/src/validation/content.ts, packages/updatePrescriptionStatus/tests/validation/testRequestContentValidation.test.ts
Adds validation for update status
=> Fix: [AEA-4369] - Validates update status

.github/workflows/delete_old_cloudformation_stacks.yml
- delete old stacks and proxygen deployments in parallel
=> Fix: [AEA-0000] - delete stacks and proxygen in parallel

scripts/run_regression_tests.py
- use a known good version of regression tests repo
=> Fix: [AEA-0000] - use a known good version of regression tests

.github/workflows/quality_checks.yml, packages/cpsuLambda/src/schema/format_1/transformer.ts, packages/cpsuLambda/tests/format_1/business_states.test.ts
- fix date format in format 1 transform
=> Fix: [AEA-4500] - fix date format

SAMtemplates/apis/main.yaml
- handle single quotes in body of request
=> Fix: [AEA-4505] - handle single quotes in format 1 body

SAMtemplates/apis/main.yaml
- force api gateway redeployment
=> Fix: [AEA-4505] - force api redeployment

.github/scripts/deploy_api.sh
- disable APIM monitoring for pull request
=> Fix: [AEA-0000] - disable APIM monitoring for pull request

.github/actions/mark_jira_released/action.yml, .github/actions/update_confluence_jira/action.yml, .github/workflows/delete_old_cloudformation_stacks.yml, .github/workflows/run_release_code_and_api.yml
-  fix AWS session name in github actions
=> Chore: [AEA-0000] - fix AWS session name in github actions

packages/specification/eps-custom-prescription-status-update-api.yaml
**Remove items from this list if they are not relevant. Remove this line once this has been done**
Update the OAS with some new text.
=> Update: [AEA-4827] - Update who can use this api section

.github/workflows/ci.yml, .github/workflows/combine-dependabot-prs.yml, .github/workflows/delete_old_cloudformation_stacks.yml, .github/workflows/dependabot_auto_approve_and_merge.yml, .github/workflows/pr-link.yml, .github/workflows/pr_title_check.yml, .github/workflows/pull_request.yml, .github/workflows/release.yml, .github/workflows/run_package_code_and_api.yml, .github/workflows/run_regression_tests.yml, .github/workflows/run_release_code_and_api.yml
- pin ubuntu image used by github runners
=> Fix: [AEA-0000] - pin ubuntu version used by github runner

poetry.lock, pyproject.toml
=> Fix: [AEA-0000] - update poetry.lock file

SAMtemplates/tables/main.yaml
- :warning: Potential issues that might be caused by this change
Finally add a GSI to the notification state table.
=> Fix: [AEA-0000] - Add GSI to the table

.github/workflows/run_regression_tests.yml
- no environment for regression test
=> Fix: [AEA-0000] - no env for regression

.github/workflows/pull_request.yml, SAMtemplates/functions/main.yaml, package-lock.json, packages/nhsNotifyLambda/package.json, packages/nhsNotifyLambda/src/utils/auth.ts, packages/nhsNotifyLambda/src/utils/notify.ts, packages/nhsNotifyLambda/tests/testAuth.test.ts, packages/nhsNotifyLambda/tests/testUtils.test.ts
=> Fix: [AEA-0000] - Implement bearer token exchange in notify request

packages/nhsNotifyLambda/src/utils/dynamo.ts, packages/nhsNotifyLambda/tests/testUtils.test.ts
A small number of patients are getting lots of notifications. 
The cooldown check was only grabbing one record from the table - I'd thought that if you sort by ODS code, then the latest record would be at the top. This is not true, so we can be checking against old records when newer ones exist.
In some rare cases (approx 1 in 10,000), a patient may get a LOT of PSU requests about their medications. In one case study, a patient had 61 distinct PSU requests pertaining to 6 prescription IDs, of which 24 requests were ready to collect. All of that was from one ODS code. This resulted in 5 SQS messages being posted ~5 minutes apart. However, when the cooldown check came for subsequent requests, it always passed. I believe this is because the cooldown check is essentially a …
=> Fix: [AEA-5722] - Fix cooldown checking bug in notify processor lambda
